[color-theme]
name = 'GitHub Dark Dimmed'

[color-theme.base]
black = '#282C34'
blue = '#61AFEF'
current-background = '#373e47'
cyan = '#56B6C2'
dim-text = '#5C6370'
green = '#98C379'
grey = '#3E4451'
magenta = '#C678DD'
orange = '#D19A66'
primary-background = '#22272e'
purple = '#C678DD'
red = '#E06C75'
secondary-background = '#1c2128'
text = '$white'
white = '#ABB2BF'
yellow = '#E5C07B'

[color-theme.syntax]
attribute = '$purple'
"bracket.color.1" = '#6cb6ff'
"bracket.color.2" = '#6bc46d'
"bracket.color.3" = '#daaa3f'
"bracket.unpaired" = '#ff938a'
builtinType = '$cyan'
comment = '#474e57'
constant = '#539bf5'
constructor = '$yellow'
embedded = '$cyan'
enum = '$yellow'
enum-member = '#539bf5'
enumMember = '#539bf5'
escape = '$cyan'
field = '$red'
function = '#dcbdfb'
"function.method" = '#dcbdfb'
interface = '$yellow'
keyword = '#f47067'
method = '#dcbdfb'
number = '$yellow'
property = '$red'
"punctuation.delimiter" = '$yellow'
selfKeyword = '$purple'
string = '#96d0ff'
"string.escape" = '#f47067'
struct = '$yellow'
structure = '$yellow'
tag = '$blue'
"text.reference" = '$yellow'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$yellow'
"type.builtin" = '$cyan'
typeAlias = '$yellow'
variable = '#f69d50'
"variable.other.member" = '$red'

[color-theme.ui]
"activity.background" = '$secondary-background'
"activity.current" = '$primary-background'
"completion.background" = '$secondary-background'
"completion.current" = '$current-background'
"completion_lens.foreground" = '$dim-text'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C7566'
"editor.background" = '$primary-background'
"editor.caret" = '#478be6'
"editor.current_line" = '#2C313C'
"editor.debug_break_line" = '#528abF37'
"editor.dim" = '$dim-text'
"editor.drag_drop_background" = '#79c1fc55'
"editor.drag_drop_tab_background" = '#0b0e1455'
"editor.focus" = '#CCCCCC'
"editor.foreground" = '$text'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '$grey'
"editor.sticky_header_background" = '$primary-background'
"editor.visible_whitespace" = '$grey'
"error_lens.error.background" = '#E06C7520'
"error_lens.error.foreground" = '$red'
"error_lens.other.background" = '#5C637020'
"error_lens.other.foreground" = '$dim-text'
"error_lens.warning.background" = '#E5C07B20'
"error_lens.warning.foreground" = '$yellow'
"hover.background" = '$secondary-background'
"inlay_hint.background" = '#528abF37'
"inlay_hint.foreground" = '$text'
"lapce.border" = '#3d444d'
"lapce.button.primary.background" = '#50a14f'
"lapce.button.primary.foreground" = '$black'
"lapce.dropdown_shadow" = '#000000'
"lapce.error" = '$red'
"lapce.icon.active" = '$text'
"lapce.icon.inactive" = '$dim-text'
"lapce.plugin.author" = '#B0B0B0'
"lapce.plugin.description" = '$text'
"lapce.plugin.name" = '#DDDDDD'
"lapce.remote.connected" = '#50A14F'
"lapce.remote.connecting" = '#C18401'
"lapce.remote.disconnected" = '#E45649'
"lapce.remote.icon" = '$black'
"lapce.remote.local" = '#4078F2'
"lapce.scroll_bar" = '#3E4451BB'
"lapce.tab.active.background" = '$primary-background'
"lapce.tab.active.foreground" = '$text'
"lapce.tab.active.underline" = '#ec775c'
"lapce.tab.inactive.background" = '$secondary-background'
"lapce.tab.inactive.foreground" = '$text'
"lapce.tab.inactive.underline" = '#528BFF77'
"lapce.tab.separator" = ''
"lapce.warn" = '$yellow'
"markdown.blockquote" = '#898989'
"palette.background" = '$secondary-background'
"palette.current.background" = '$current-background'
"palette.current.foreground" = '$text'
"palette.foreground" = '$text'
"panel.background" = '$secondary-background'
"panel.current.background" = '$current-background'
"panel.current.foreground" = '$text'
"panel.current.foreground.dim" = '$dim-text'
"panel.foreground" = '$text'
"panel.foreground.dim" = '$dim-text'
"panel.hovered.active.background" = '$dim-text'
"panel.hovered.background" = '#343A45'
"panel.hovered.foreground" = '$text'
"panel.hovered.foreground.dim" = '$dim-text'
"source_control.added" = '#57ab5a'
"source_control.modified" = '#c69026'
"source_control.removed" = '#FF5266CC'
"status.background" = '$secondary-background'
"status.foreground" = '$text'
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '$black'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '$black'
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$black'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$black'
"terminal.background" = '$primary-background'
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#545862'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '#C8CCD4'
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '$text'
"terminal.cyan" = '$cyan'
"terminal.foreground" = '#adbac7'
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$white'
"terminal.yellow" = '$yellow'
"tooltip.background" = '$primary-background'
"tooltip.foreground" = '$text'
